-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/
-- Load Wallust-generated colors

-- After all hl.env() lines:
hl.env("PATH", "/home/dhp/.local/bin:/home/dhp/bin:/usr/local/sbin:/usr/local/bin:/usr/bin")

local function set_wallpaper(path)
    local conf = io.open(os.getenv("HOME") .. "/.config/hypr/hyprpaper.conf", "w")
    if conf then
        conf:write("preload = " .. path .. "\n")
        conf:write("wallpaper = ," .. path .. "\n")
        conf:write("splash = false\n")
        conf:write("ipc = on\n")
        conf:close()
    end
    hl.exec_cmd("pkill -x hyprpaper; sleep 0.3; hyprpaper &")
end
-- Load Ambxst-generated border colors from axctl.toml
local function load_ambxst_borders()
    local path = os.getenv("HOME") .. "/.local/share/ambxst/axctl.toml"
    local f = io.open(path, "r")
    if not f then return end

    local active, inactive, width = nil, nil, nil
    local in_section = false
    for line in f:lines() do
        if line:match("^%[appearance%.border%]") then
            in_section = true
        elseif line:match("^%[") then
            in_section = false
        elseif in_section then
            local k, v = line:match('^(%w+)%s*=%s*"([^"]+)"')
            if k == "active_color" then active = v
            elseif k == "inactive_color" then inactive = v
            end
            local w = line:match('^width%s*=%s*(%d+)')
            if w then width = tonumber(w) end
        end
    end
    f:close()

    if active and inactive then
        -- Strip "rgb(...)" wrapper, Hyprland expects hex without #
        local a = active:match("rgb%((%w+)%)")
        local i = inactive:match("rgb%((%w+)%)")
        if a and i then
            hl.config({
                general = {
                    border_size = width or 2,
                    col = {
                        active_border = { colors = { "rgb(" .. a .. ")", "rgb(" .. a .. ")" }, angle = 45 },
                        inactive_border = "rgb(" .. i .. ")",
                    },
                },
            })
        end
    end
end

load_ambxst_borders()



------------------
---- MONITORS ----
------------------

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@60",
	position = "auto",
	scale = "1",
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal = "kitty"
local fileManager = "nautilus"
local menu = "ambxst run launcher"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function ()
    hl.exec_cmd("pkill slurp 2>/dev/null")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("/home/dhp/.local/bin/ambxst")
    hl.exec_cmd("sleep 1; bash ~/.config/hypr/scripts/theme.sh /home/dhp/Pictures/wallpapers/image.png")
end)


-------------------
---- WALLPAPER ----
-------------------

-- Delegate wallpaper + theming to a single script
-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 8,

		border_size = 2,



		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 12,
		rounding_power = 2,

		active_opacity = 1,
		inactive_opacity = 0.88,

		shadow = {
			enabled = true,
			range = 10,
			render_power = 3,
			color = 0x99080c0e,
		},

		blur = {
			enabled = true,
			size = 8,
			passes = 4,
			vibrancy = 0.2,
		},
	},

	animations = {
		enabled = true,
	},
})




-- Curves and animations
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

hl.config({
	dwindle = {
		preserve_split = true,
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = false,
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,
		sensitivity = 0,

		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})





---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + w", hl.dsp.window.close())
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(
    mainMod .. " + V",
    hl.dsp.window.fullscreen({
        mode = "maximized",
        action = "toggle"
    })
)
hl.bind("SUPER + B", hl.dsp.exec_cmd("/home/dhp/bin/rice-mode.sh toggle"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- Screenshot Region to Clipboard & Save to Pictures via Alt + Shift + S
hl.bind("ALT + SHIFT + S", hl.dsp.exec_cmd('grim -g "$(slurp)" - | tee ~/Pictures/screenshot_$(date +%Y%m%d_%H%M%S).png | wl-copy'))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
for i = 1, 10 do
	local key = i % 10
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Multimedia keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },
	move = "20 monitor_h-120",
	float = true,
})


-- ═══ Ambxst keybinds (absolute paths) ═══
hl.bind("SUPER + R", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run launcher"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run dashboard"))
hl.bind("SUPER + A", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run assistant"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run clipboard"))
hl.bind("SUPER + PERIOD", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run emoji"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run notes"))
hl.bind("SUPER + T", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run tmux"))
hl.bind("SUPER + COMMA", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run wallpapers"))
hl.bind("SUPER + TAB", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run overview"))
hl.bind("SUPER + ESCAPE", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run powermenu"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run config"))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run screenshot"))
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run screenrecord"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run lens"))
hl.bind("SUPER + S", hl.dsp.exec_cmd("/home/dhp/.local/bin/ambxst run tools"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))

-- PATH fix for Hyprland-spawned commands
hl.env("PATH", "/home/dhp/.local/bin:/home/dhp/bin:" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin"))
